import React, { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { Calendar, Clock, ArrowLeft, AlertCircle, FileText, X, Download, Receipt } from 'lucide-react';
import { downloadReportPDF, downloadAppointmentSlip, downloadPaymentReceipt } from '../utils/pdfGenerator';
import ThemeToggle from '../components/ThemeToggle';
import AppointmentCalendar from '../components/AppointmentCalendar';
import { fetchAppointments, selectAppointments, cancelAppointment } from '../redux/slices/appointmentSlice';
import { fetchPatientReports, addReportFromSocket, selectReports } from '../redux/slices/reportSlice';
import { initSocket, disconnectSocket } from '../api/socketClient';

const MyAppointments = () => {
    const dispatch = useDispatch();
    const navigate = useNavigate();

    const appointments = useSelector(selectAppointments);
    const { loading } = useSelector(state => state.appointments);
    const reports = useSelector(selectReports);
    const user = useSelector(state => state.auth.user);

    const [activeTab, setActiveTab] = useState('upcoming'); // 'upcoming', 'history'
    const [view, setView] = useState('list'); // 'list' | 'calendar'
    const [cancellingId, setCancellingId] = useState(null);

    // Report View Modal
    const [selectedReport, setSelectedReport] = useState(null);

    useEffect(() => {
        dispatch(fetchAppointments());
        const userId = user?.id || user?._id;
        if (userId) {
            dispatch(fetchPatientReports(userId));

            // Initialize Socket for Real-time updates
            const socket = initSocket(userId);
            socket.on('new_report', (report) => {
                // console.log("New Report Received via Socket:", report);
                dispatch(addReportFromSocket(report));
                // Optional: Show a toast/notification
                alert(`New medical report generated by Dr. ${report.doctorId?.name || 'Unknown'}`);
            });

            return () => {
                socket.off('new_report');
                disconnectSocket();
            }
        }
    }, [dispatch, user]);

    const handleCancel = async (appt) => {
        if (!window.confirm("Are you sure you want to cancel this appointment?")) return;

        setCancellingId(appt._id);
        try {
            const result = await dispatch(cancelAppointment(appt._id)).unwrap();
            const { refundPercentage, refundAmount, message } = result;

            alert(`${message}\nRefund: ${refundPercentage}% (₹${refundAmount})`);
        } catch (error) {
            console.error("Cancellation failed", error);
            alert(error || "Failed to cancel appointment");
        } finally {
            setCancellingId(null);
        }
    };

    const handleViewReport = (apptId) => {
        const report = reports.find(r =>
            // Handle both object populated ID and string ID
            (r.appointmentId?._id === apptId) || (r.appointmentId === apptId)
        );

        // console.log("Looking for report for appt:", apptId, "Found:", report);

        if (report) {
            setSelectedReport(report);
        } else {
            alert("Report not found for this appointment.");
        }
    };

    if (loading) {
        return (
            <div className="min-h-screen bg-gray-50 dark:bg-zinc-900 flex items-center justify-center">
                <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-600"></div>
            </div>
        );
    }

    const currentList = activeTab === 'upcoming'
        ? (appointments.upcoming || [])
        : (appointments.history || []);

    // Combine for calendar
    const allAppointments = [...(appointments.upcoming || []), ...(appointments.history || [])];

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-zinc-900 transition-colors p-4 sm:p-8 relative">
            <div className="max-w-4xl mx-auto">
                {/* Header */}
                <div className="flex justify-between items-center mb-8">
                    <div className="flex items-center gap-4">
                        <button
                            onClick={() => navigate(-1)}
                            className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-zinc-800 transition-colors"
                        >
                            <ArrowLeft className="text-gray-600 dark:text-gray-300" />
                        </button>
                        <h1 className="text-3xl font-bold text-gray-900 dark:text-white">My Appointments</h1>
                    </div>
                    <div className="flex items-center gap-4">
                        <button
                            onClick={() => navigate('/patient/reports')}
                            className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 rounded-lg text-sm font-medium text-gray-600 dark:text-gray-300 hover:border-blue-500 transition-colors shadow-sm"
                        >
                            <FileText size={16} /> My Reports
                        </button>
                        <ThemeToggle />
                    </div>
                </div>

                {/* View Toggles & Tabs */}
                {/* ... (Keep existing toggles unchanged, just re-rendering) ... */}
                <div className="flex flex-col sm:flex-row gap-4 mb-8 justify-between">
                    <div className="flex bg-gray-200 dark:bg-zinc-700 p-1 rounded-lg self-start">
                        <button onClick={() => setView('list')} className={`px-4 py-2 rounded-md text-sm font-semibold transition-colors ${view === 'list' ? 'bg-white dark:bg-zinc-600 shadow-sm text-blue-600 dark:text-blue-400' : 'text-gray-500 dark:text-gray-400'}`}>List</button>
                        <button onClick={() => setView('calendar')} className={`px-4 py-2 rounded-md text-sm font-semibold transition-colors ${view === 'calendar' ? 'bg-white dark:bg-zinc-600 shadow-sm text-blue-600 dark:text-blue-400' : 'text-gray-500 dark:text-gray-400'}`}>Calendar</button>
                    </div>

                    {view === 'list' && (
                        <div className="flex bg-white dark:bg-zinc-800 rounded-2xl shadow-sm border border-gray-100 dark:border-zinc-700 p-1 flex-1 sm:max-w-md">
                            <button onClick={() => setActiveTab('upcoming')} className={`flex-1 py-2 rounded-xl text-sm font-semibold transition-all ${activeTab === 'upcoming' ? 'bg-blue-600 text-white shadow-md' : 'text-gray-500 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-zinc-700'}`}>Upcoming</button>
                            <button onClick={() => setActiveTab('history')} className={`flex-1 py-2 rounded-xl text-sm font-semibold transition-all ${activeTab === 'history' ? 'bg-blue-600 text-white shadow-md' : 'text-gray-500 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-zinc-700'}`}>History</button>
                        </div>
                    )}
                </div>

                {view === 'calendar' ? (
                    <div className="bg-white dark:bg-zinc-800 p-2 rounded-2xl shadow-sm border border-gray-100 dark:border-zinc-700">
                        <AppointmentCalendar appointments={allAppointments} userRole="patient" />
                    </div>
                ) : (
                    <div className="space-y-4">
                        {currentList.length > 0 ? currentList.map(appt => {
                            // Check if report exists for this appointment
                            const hasReport = reports.some(r => (r.appointmentId?._id === appt._id) || (r.appointmentId === appt._id));

                            return (
                                <div key={appt._id} className="bg-white dark:bg-zinc-800 p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-zinc-700 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 group hover:border-blue-500 transition-all">
                                    <div className="flex items-center gap-4">
                                        <div className="w-16 h-16 rounded-full bg-blue-50 dark:bg-blue-900/20 flex items-center justify-center flex-shrink-0 text-blue-600 dark:text-blue-400 font-bold text-xl">
                                            {new Date(appt.date).getDate()}
                                        </div>
                                        <div>
                                            <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-1">
                                                {appt.doctorName || "Dr. Unknown"}
                                            </h3>
                                            <p className="text-blue-600 dark:text-blue-400 text-sm mb-2">{appt.type || "Checkup"}</p>
                                            <div className="flex items-center gap-4 text-sm text-gray-500 dark:text-gray-400">
                                                <div className="flex items-center gap-1"><Calendar size={14} />{new Date(appt.date).toLocaleDateString()}</div>
                                                <div className="flex items-center gap-1"><Clock size={14} />{appt.time}</div>
                                            </div>
                                            {appt.amount && (
                                                <div className="mt-2 text-sm text-gray-500 dark:text-gray-400 flex items-center gap-2">
                                                    <span>Fee: ₹{appt.amount}</span>
                                                    <span className={`text-xs px-2 py-0.5 rounded-full border ${appt.paymentStatus === 'Paid' ? 'bg-green-100 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-400 dark:border-green-800' : 'bg-orange-100 text-orange-700 border-orange-200 dark:bg-orange-900/30 dark:text-orange-400 dark:border-orange-800'}`}>
                                                        {appt.paymentStatus || 'Pending'} {appt.paymentMethod === 'Cash' ? '(Pay at Clinic)' : null}
                                                    </span>
                                                    {appt.status === 'cancelled' && appt.refundAmount !== undefined && (
                                                        <span className="text-green-600 font-medium">(Refunded: ₹{appt.refundAmount})</span>
                                                    )}
                                                </div>
                                            )}
                                            <div className="text-xs text-gray-400 mt-1">
                                                Booked on: {new Date(appt.createdAt).toLocaleString()}
                                            </div>
                                        </div>
                                    </div>

                                    <div className="flex flex-col items-end gap-2 w-full sm:w-auto">
                                        <span className={`px-3 py-1 rounded-full text-xs font-semibold ${appt.status === 'confirmed' ? 'bg-green-100 text-green-700' : appt.status === 'cancelled' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700'}`}>
                                            {appt.status}
                                        </span>

                                        {/* Download Buttons */}
                                        <div className="flex gap-2 mt-2">
                                            {activeTab === 'upcoming' && appt.status !== 'cancelled' && (
                                                <button
                                                    onClick={() => downloadAppointmentSlip({ ...appt, patientName: user?.name })}
                                                    className="p-1.5 text-blue-600 hover:bg-blue-50 rounded-lg title='Download Slip'"
                                                    title="Download Appointment Slip"
                                                >
                                                    <Download size={18} />
                                                </button>
                                            )}
                                            {appt.status === 'confirmed' && (
                                                <button
                                                    onClick={() => downloadPaymentReceipt({ ...appt, patientName: user?.name })}
                                                    className="p-1.5 text-green-600 hover:bg-green-50 rounded-lg title='Download Receipt'"
                                                    title="Download Payment Receipt"
                                                >
                                                    <Receipt size={18} />
                                                </button>
                                            )}
                                        </div>

                                        {/* View Report Button */}
                                        {hasReport && (
                                            <button
                                                onClick={() => handleViewReport(appt._id)}
                                                className="flex items-center gap-1 px-4 py-2 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-lg hover:bg-blue-100 dark:hover:bg-blue-900/40 transition-colors font-medium text-sm mt-2"
                                            >
                                                <FileText size={16} /> View Report
                                            </button>
                                        )}

                                        {activeTab === 'upcoming' && appt.status !== 'cancelled' && (
                                            <button
                                                onClick={() => handleCancel(appt)}
                                                disabled={cancellingId === appt._id}
                                                className="text-sm text-red-500 hover:text-red-700 hover:underline mt-2 disabled:opacity-50"
                                            >
                                                {cancellingId === appt._id ? "Processing..." : "Cancel Appointment"}
                                            </button>
                                        )}
                                    </div>
                                </div>
                            );
                        }) : (
                            <div className="text-center py-12">
                                <div className="bg-gray-100 dark:bg-zinc-800 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4 text-gray-400">
                                    <Calendar size={32} />
                                </div>
                                <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">No Appointments</h3>
                                <p className="text-gray-500 dark:text-gray-400">You don't have any appointments in this list.</p>
                                {activeTab === 'upcoming' && (
                                    <button onClick={() => navigate('/book-appointment')} className="mt-6 px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors">Book Now</button>
                                )}
                            </div>
                        )}
                    </div>
                )}
            </div>

            {/* View Report Modal */}
            {selectedReport && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
                    <div className="bg-white dark:bg-zinc-900 w-full max-w-lg rounded-2xl shadow-xl overflow-hidden animate-in fade-in zoom-in duration-200">
                        <div className="p-6 border-b border-gray-100 dark:border-zinc-800 flex justify-between items-center bg-blue-600 text-white">
                            <div>
                                <h3 className="text-xl font-bold">Medical Report</h3>
                                <p className="text-sm text-blue-100 opacity-90">Dr. {selectedReport.doctorId?.name}</p>
                            </div>
                            <div className="flex items-center gap-3">
                                <button
                                    onClick={() => downloadReportPDF(selectedReport)}
                                    className="text-white/80 hover:text-white transition-colors flex items-center gap-1 text-sm font-medium"
                                >
                                    <Download size={18} /> PDF
                                </button>
                                <button onClick={() => setSelectedReport(null)} className="text-white/80 hover:text-white transition-colors">
                                    <X size={24} />
                                </button>
                            </div>
                        </div>

                        <div className="p-6 max-h-[70vh] overflow-y-auto space-y-6">
                            {/* Diagnosis Section */}
                            <div className="bg-blue-50 dark:bg-blue-900/10 p-4 rounded-xl">
                                <h4 className="font-semibold text-blue-800 dark:text-blue-300 mb-2 flex items-center gap-2">
                                    <AlertCircle size={18} /> Diagnosis
                                </h4>
                                <p className="text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-wrap">
                                    {selectedReport.diagnosis}
                                </p>
                            </div>

                            {/* Prescriptions Section */}
                            <div>
                                <h4 className="font-semibold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                                    <FileText size={18} /> Prescriptions
                                </h4>
                                {selectedReport.prescriptions && selectedReport.prescriptions.length > 0 ? (
                                    <div className="border border-gray-100 dark:border-zinc-700 rounded-xl overflow-hidden">
                                        <table className="w-full text-left text-sm">
                                            <thead className="bg-gray-50 dark:bg-zinc-800 text-gray-600 dark:text-gray-400">
                                                <tr>
                                                    <th className="px-4 py-3 font-medium">Medicine</th>
                                                    <th className="px-4 py-3 font-medium">Frequency</th>
                                                    <th className="px-4 py-3 font-medium">Duration</th>
                                                </tr>
                                            </thead>
                                            <tbody className="divide-y divide-gray-100 dark:divide-zinc-700">
                                                {selectedReport.prescriptions.map((p, idx) => (
                                                    <tr key={idx} className="hover:bg-gray-50 dark:hover:bg-zinc-800/50">
                                                        <td className="px-4 py-3 text-gray-900 dark:text-white font-medium">{p.medicine}</td>
                                                        <td className="px-4 py-3 text-gray-600 dark:text-gray-300">
                                                            <span className="px-2 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded text-xs font-semibold">
                                                                {p.frequency}
                                                            </span>
                                                        </td>
                                                        <td className="px-4 py-3 text-gray-500 dark:text-gray-400">{p.duration || "-"}</td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                ) : (
                                    <p className="text-gray-500 dark:text-gray-400 italic">No prescriptions added.</p>
                                )}
                            </div>

                            <div className="text-xs text-gray-400 text-center mt-4">
                                Generated on {new Date(selectedReport.createdAt).toLocaleString()}
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default MyAppointments;
